name: Packer status check workflow

on:
  pull_request:
    branches:
      - main
 
jobs:
  test:
    name: Packer Workflow
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{secrets.DB_HOST }}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
      AWS_REGION: ${{secrets.AWS_REGION}}
    
      INSTANCE_TYPE: ${{secrets.INSTANCE_TYPE}}
      SSH_USERNAME: ${{secrets.SSH_USERNAME}}
      SUBNET_ID: ${{secrets.SUBNET_ID}}
      VPC_ID: ${{secrets.VPC_ID}}
      
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
          unzip packer_1.11.2_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version
 
      - name: Initialize packer
        run: |
          packer init .
        shell: bash

      - name: Create webapp.zip from existing directory
        run: |
          zip -r webapp.zip .
        shell: bash
      
      - name: Format packer
        run: |
          packer fmt -check csye6225-aws.pkr.hcl
        continue-on-error: false
        shell: bash
        
      - name: Validate Packer
        run: |
          packer validatecsye6225-aws.pkr.hcl
        shell: bash