name: Web App CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Web App Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --user=$DB_USER --password=$DB_PASSWORD" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Load Environment Variables
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to start..."
          sleep 20
          until mysql --host=127.0.0.1 --port=3306 --user=$DB_USER --password=$DB_PASSWORD -e "SHOW DATABASES;"; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready."

      - name: Ensure Correct Authentication Method
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=$DB_PASSWORD -e "ALTER USER '$DB_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$DB_PASSWORD'; FLUSH PRIVILEGES;"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
